// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: artifact.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/hmsoft0815/mlcartifact/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArtifactServiceName is the fully-qualified name of the ArtifactService service.
	ArtifactServiceName = "artifact.v1.ArtifactService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArtifactServiceWriteProcedure is the fully-qualified name of the ArtifactService's Write RPC.
	ArtifactServiceWriteProcedure = "/artifact.v1.ArtifactService/Write"
	// ArtifactServiceReadProcedure is the fully-qualified name of the ArtifactService's Read RPC.
	ArtifactServiceReadProcedure = "/artifact.v1.ArtifactService/Read"
	// ArtifactServiceDeleteProcedure is the fully-qualified name of the ArtifactService's Delete RPC.
	ArtifactServiceDeleteProcedure = "/artifact.v1.ArtifactService/Delete"
	// ArtifactServiceListProcedure is the fully-qualified name of the ArtifactService's List RPC.
	ArtifactServiceListProcedure = "/artifact.v1.ArtifactService/List"
	// ArtifactServicePatchProcedure is the fully-qualified name of the ArtifactService's Patch RPC.
	ArtifactServicePatchProcedure = "/artifact.v1.ArtifactService/Patch"
	// ArtifactServiceFindProcedure is the fully-qualified name of the ArtifactService's Find RPC.
	ArtifactServiceFindProcedure = "/artifact.v1.ArtifactService/Find"
)

// ArtifactServiceClient is a client for the artifact.v1.ArtifactService service.
type ArtifactServiceClient interface {
	Write(context.Context, *connect.Request[proto.WriteRequest]) (*connect.Response[proto.WriteResponse], error)
	Read(context.Context, *connect.Request[proto.ReadRequest]) (*connect.Response[proto.ReadResponse], error)
	Delete(context.Context, *connect.Request[proto.DeleteRequest]) (*connect.Response[proto.DeleteResponse], error)
	List(context.Context, *connect.Request[proto.ListRequest]) (*connect.Response[proto.ListResponse], error)
	// VFS: Hierarchical Virtual File System operations
	Patch(context.Context, *connect.Request[proto.PatchRequest]) (*connect.Response[proto.PatchResponse], error)
	Find(context.Context, *connect.Request[proto.FindRequest]) (*connect.Response[proto.ListResponse], error)
}

// NewArtifactServiceClient constructs a client for the artifact.v1.ArtifactService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactServiceMethods := proto.File_artifact_proto.Services().ByName("ArtifactService").Methods()
	return &artifactServiceClient{
		write: connect.NewClient[proto.WriteRequest, proto.WriteResponse](
			httpClient,
			baseURL+ArtifactServiceWriteProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Write")),
			connect.WithClientOptions(opts...),
		),
		read: connect.NewClient[proto.ReadRequest, proto.ReadResponse](
			httpClient,
			baseURL+ArtifactServiceReadProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Read")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[proto.DeleteRequest, proto.DeleteResponse](
			httpClient,
			baseURL+ArtifactServiceDeleteProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[proto.ListRequest, proto.ListResponse](
			httpClient,
			baseURL+ArtifactServiceListProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		patch: connect.NewClient[proto.PatchRequest, proto.PatchResponse](
			httpClient,
			baseURL+ArtifactServicePatchProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Patch")),
			connect.WithClientOptions(opts...),
		),
		find: connect.NewClient[proto.FindRequest, proto.ListResponse](
			httpClient,
			baseURL+ArtifactServiceFindProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("Find")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactServiceClient implements ArtifactServiceClient.
type artifactServiceClient struct {
	write  *connect.Client[proto.WriteRequest, proto.WriteResponse]
	read   *connect.Client[proto.ReadRequest, proto.ReadResponse]
	delete *connect.Client[proto.DeleteRequest, proto.DeleteResponse]
	list   *connect.Client[proto.ListRequest, proto.ListResponse]
	patch  *connect.Client[proto.PatchRequest, proto.PatchResponse]
	find   *connect.Client[proto.FindRequest, proto.ListResponse]
}

// Write calls artifact.v1.ArtifactService.Write.
func (c *artifactServiceClient) Write(ctx context.Context, req *connect.Request[proto.WriteRequest]) (*connect.Response[proto.WriteResponse], error) {
	return c.write.CallUnary(ctx, req)
}

// Read calls artifact.v1.ArtifactService.Read.
func (c *artifactServiceClient) Read(ctx context.Context, req *connect.Request[proto.ReadRequest]) (*connect.Response[proto.ReadResponse], error) {
	return c.read.CallUnary(ctx, req)
}

// Delete calls artifact.v1.ArtifactService.Delete.
func (c *artifactServiceClient) Delete(ctx context.Context, req *connect.Request[proto.DeleteRequest]) (*connect.Response[proto.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls artifact.v1.ArtifactService.List.
func (c *artifactServiceClient) List(ctx context.Context, req *connect.Request[proto.ListRequest]) (*connect.Response[proto.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Patch calls artifact.v1.ArtifactService.Patch.
func (c *artifactServiceClient) Patch(ctx context.Context, req *connect.Request[proto.PatchRequest]) (*connect.Response[proto.PatchResponse], error) {
	return c.patch.CallUnary(ctx, req)
}

// Find calls artifact.v1.ArtifactService.Find.
func (c *artifactServiceClient) Find(ctx context.Context, req *connect.Request[proto.FindRequest]) (*connect.Response[proto.ListResponse], error) {
	return c.find.CallUnary(ctx, req)
}

// ArtifactServiceHandler is an implementation of the artifact.v1.ArtifactService service.
type ArtifactServiceHandler interface {
	Write(context.Context, *connect.Request[proto.WriteRequest]) (*connect.Response[proto.WriteResponse], error)
	Read(context.Context, *connect.Request[proto.ReadRequest]) (*connect.Response[proto.ReadResponse], error)
	Delete(context.Context, *connect.Request[proto.DeleteRequest]) (*connect.Response[proto.DeleteResponse], error)
	List(context.Context, *connect.Request[proto.ListRequest]) (*connect.Response[proto.ListResponse], error)
	// VFS: Hierarchical Virtual File System operations
	Patch(context.Context, *connect.Request[proto.PatchRequest]) (*connect.Response[proto.PatchResponse], error)
	Find(context.Context, *connect.Request[proto.FindRequest]) (*connect.Response[proto.ListResponse], error)
}

// NewArtifactServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactServiceHandler(svc ArtifactServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactServiceMethods := proto.File_artifact_proto.Services().ByName("ArtifactService").Methods()
	artifactServiceWriteHandler := connect.NewUnaryHandler(
		ArtifactServiceWriteProcedure,
		svc.Write,
		connect.WithSchema(artifactServiceMethods.ByName("Write")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceReadHandler := connect.NewUnaryHandler(
		ArtifactServiceReadProcedure,
		svc.Read,
		connect.WithSchema(artifactServiceMethods.ByName("Read")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceDeleteHandler := connect.NewUnaryHandler(
		ArtifactServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(artifactServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceListHandler := connect.NewUnaryHandler(
		ArtifactServiceListProcedure,
		svc.List,
		connect.WithSchema(artifactServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServicePatchHandler := connect.NewUnaryHandler(
		ArtifactServicePatchProcedure,
		svc.Patch,
		connect.WithSchema(artifactServiceMethods.ByName("Patch")),
		connect.WithHandlerOptions(opts...),
	)
	artifactServiceFindHandler := connect.NewUnaryHandler(
		ArtifactServiceFindProcedure,
		svc.Find,
		connect.WithSchema(artifactServiceMethods.ByName("Find")),
		connect.WithHandlerOptions(opts...),
	)
	return "/artifact.v1.ArtifactService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactServiceWriteProcedure:
			artifactServiceWriteHandler.ServeHTTP(w, r)
		case ArtifactServiceReadProcedure:
			artifactServiceReadHandler.ServeHTTP(w, r)
		case ArtifactServiceDeleteProcedure:
			artifactServiceDeleteHandler.ServeHTTP(w, r)
		case ArtifactServiceListProcedure:
			artifactServiceListHandler.ServeHTTP(w, r)
		case ArtifactServicePatchProcedure:
			artifactServicePatchHandler.ServeHTTP(w, r)
		case ArtifactServiceFindProcedure:
			artifactServiceFindHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactServiceHandler struct{}

func (UnimplementedArtifactServiceHandler) Write(context.Context, *connect.Request[proto.WriteRequest]) (*connect.Response[proto.WriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("artifact.v1.ArtifactService.Write is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Read(context.Context, *connect.Request[proto.ReadRequest]) (*connect.Response[proto.ReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("artifact.v1.ArtifactService.Read is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Delete(context.Context, *connect.Request[proto.DeleteRequest]) (*connect.Response[proto.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("artifact.v1.ArtifactService.Delete is not implemented"))
}

func (UnimplementedArtifactServiceHandler) List(context.Context, *connect.Request[proto.ListRequest]) (*connect.Response[proto.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("artifact.v1.ArtifactService.List is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Patch(context.Context, *connect.Request[proto.PatchRequest]) (*connect.Response[proto.PatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("artifact.v1.ArtifactService.Patch is not implemented"))
}

func (UnimplementedArtifactServiceHandler) Find(context.Context, *connect.Request[proto.FindRequest]) (*connect.Response[proto.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("artifact.v1.ArtifactService.Find is not implemented"))
}
