version: 2

# This is the configuration for GoReleaser
# It will build binaries for Windows, Linux, and macOS.

before:
  hooks:
    - go mod tidy

builds:
  - id: artifact-server
    main: ./cmd/server
    binary: artifact-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: artifact-cli
    main: ./cmd/cli/cmd/artifact-cli
    binary: artifact-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - README.de.md

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: artifact-packages
    package_name: mlcartifact
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    vendor: Michael Lechner
    homepage: https://github.com/hmsoft0815/mlcartifact
    maintainer: Michael Lechner <michael@mlcgo.eu>
    description: gRPC based artifact storage service for MCP ecosystem.
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - artifact-server
      - artifact-cli
    contents:
      - src: LICENSE
        dst: /usr/share/doc/mlcartifact/LICENSE
      - src: README.md
        dst: /usr/share/doc/mlcartifact/README.md

attest:
  - artifacts: checksum

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
