[package]
name = "mlcartifact"
version = "0.5.0"
edition = "2021"
description = "Rust client for mlcartifact service"
license = "MIT"
authors = ["Michael Lechner"]

[dependencies]
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"
tokio = { version = "1.0", features = ["full"] }
http = "1.1"

[build-dependencies]
tonic-prost-build = "0.14"
