// Copyright (c) 2026 Michael Lechner. All rights reserved.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/hmsoft0815/mlcartifact/internal/grpc"
	artifactmcp "github.com/hmsoft0815/mlcartifact/internal/mcp"
	"github.com/hmsoft0815/mlcartifact/internal/storage"
	"github.com/hmsoft0815/mlcartifact/proto/protoconnect"
	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

var (
	version = "dev"
	name    = "artifact-server"
)

func getTools() []mcp.Tool {
	return []mcp.Tool{
		mcp.NewTool(
			"write_artifact",
			mcp.WithDescription(`Saves a file (e.g., Markdown, PDF, Spreadsheet, or Code) to a secure artifact storage.
This tool returns a JSON object containing the 'id', 'filename', and 'expires_at' (ISO timestamp) of the saved artifact.
YOU MUST notify the user clearly in your final response that the file has been saved. 
Include a hint like: "The complete file is available in the artifact server under id = {id}".`),
			mcp.WithString("filename",
				mcp.Required(),
				mcp.Description("The desired name for the file (e.g., 'report.pdf', 'data.csv', 'script.py')."),
			),
			mcp.WithString("content",
				mcp.Required(),
				mcp.Description("The full text content to be saved."),
			),
			mcp.WithString("mime_type",
				mcp.Description("Optional: The MIME type of the content (e.g. 'text/markdown', 'text/csv'). If omitted, it will be detected from the filename."),
			),
			mcp.WithNumber("expires_in_hours",
				mcp.Description("Optional: Hours after which the file should be deleted (default 24)."),
			),
			mcp.WithToolIcons(mcp.Icon{
				Src:      "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPjxwYXRoIGQ9Ik0xNCAydkg2YTIgMiAwIDAgMC0yIDJ2MTZhMiAyIDAgMCAwIDIgMmgxMmEyIDIgMCAwIDAgMi0yVjhsLTYtNnoiLz48cG9seWxpbmUgcG9pbnRzPSIxNCAyIDE0IDggMjAgOCIvPjwvc3ZnPg==",
				MIMEType: "image/svg+xml",
			}),
		),
		mcp.NewTool(
			"read_artifact",
			mcp.WithDescription("Retrieves the content of a saved artifact. Use this to read data generated by other tools."),
			mcp.WithString("id", mcp.Required(), mcp.Description("The unique artifact ID or sanitized filename.")),
			mcp.WithString("user_id", mcp.Description("Optional: The user ID to scope the lookup.")),
		),
		mcp.NewTool(
			"list_artifacts",
			mcp.WithDescription("Lists all saved artifacts for a user or in the global scope."),
			mcp.WithString("user_id", mcp.Description("Optional: The user ID to scope the listing.")),
		),
		mcp.NewTool(
			"delete_artifact",
			mcp.WithDescription("Permanently deletes an artifact from the storage."),
			mcp.WithString("id", mcp.Required(), mcp.Description("The unique artifact ID or sanitized filename.")),
			mcp.WithString("user_id", mcp.Description("Optional: The user ID to scope the deletion.")),
		),
	}
}

func main() {
	dump := flag.Bool("dump", false, "Dump available tools as JSON and exit")
	v := flag.Bool("version", false, "Print version and exit")
	addr := flag.String("addr", "", "Listen address for SSE (e.g. '127.0.0.1:8080' for local only, or ':8080' for all interfaces). If empty, uses stdio.")
	grpcAddr := flag.String("grpc-addr", ":9590", "Listen address for gRPC service (e.g. '127.0.0.1:9590' for local only, or ':9590' for all interfaces)")
	mcpLimit := flag.Int("mcp-list-limit", 100, "Max artifacts to return in MCP list_artifacts")

	defaultDataDir := ".artifacts"
	if home, err := os.UserHomeDir(); err == nil {
		defaultDataDir = filepath.Join(home, "mlcartifact", "storage")
	}
	dataDir := flag.String("data-dir", defaultDataDir, "Base directory for artifact storage")
	flag.Parse()

	if *v {
		fmt.Printf("%s version: %s\n", name, version)
		return
	}

	// Initialize store and set in handlers
	store := storage.NewStore(*dataDir)
	slog.Info("initializing artifact store", "dir", *dataDir)
	artifactmcp.SetStore(store)
	artifactmcp.SetMCPListLimit(*mcpLimit)

	if *dump {
		tools := getTools()
		b, _ := json.MarshalIndent(tools, "", "  ")
		fmt.Println(string(b))
		return
	}

	mcpServer := server.NewMCPServer(
		name,
		version,
		server.WithToolCapabilities(false),
	)

	// Add tools
	for _, t := range getTools() {
		switch t.Name {
		case "write_artifact":
			mcpServer.AddTool(t, artifactmcp.WriteArtifact)
		case "read_artifact":
			mcpServer.AddTool(t, artifactmcp.ReadArtifact)
		case "list_artifacts":
			mcpServer.AddTool(t, artifactmcp.ListArtifacts)
		case "delete_artifact":
			mcpServer.AddTool(t, artifactmcp.DeleteArtifact)
		}
	}

	// Start Connect/gRPC server in background
	go func() {
		mux := http.NewServeMux()
		path, handler := protoconnect.NewArtifactServiceHandler(grpc.NewConnectServer(store))
		mux.Handle(path, handler)

		slog.Info("Connect/gRPC server started", "addr", *grpcAddr)

		// Setup CORS for browser access
		c := cors.New(cors.Options{
			AllowedOrigins: []string{"*"}, // Adjust in production
			AllowedMethods: []string{"GET", "POST", "OPTIONS"},
			AllowedHeaders: []string{"Connect-Protocol-Version", "Content-Type", "Accept", "Connect-Timeout-Ms", "X-User-Id"},
			ExposedHeaders: []string{"Content-Length"},
		})

		// We use h2c to support gRPC/HTTP2 without TLS
		if err := http.ListenAndServe(*grpcAddr, c.Handler(h2c.NewHandler(mux, &http2.Server{}))); err != nil {
			slog.Error("Connect/gRPC server failed", "err", err)
		}
	}()

	if *addr != "" {
		// SSE Mode
		host := *addr
		if strings.HasPrefix(host, ":") {
			host = "localhost" + host
		}
		sse := server.NewSSEServer(mcpServer, server.WithBaseURL(fmt.Sprintf("http://%s", host)))
		slog.Info("SSE server started", "addr", *addr, "name", name)
		if err := http.ListenAndServe(*addr, sse); err != nil {
			slog.Error("http server failed", "err", err)
			os.Exit(1)
		}
	} else {
		// Stdio Mode
		slog.Info("stdio server started", "name", name, "version", version)
		if err := server.ServeStdio(mcpServer); err != nil {
			slog.Error("fatal error", "err", err)
			os.Exit(1)
		}
	}
}
